//! SFZ sample map + rendered cycle WAV.

use crate::export::{ExportOptions, ExportReport};
use crate::patch::Patch;
use crate::voice::render_note;
use crate::wavetable::WavetableBank;
use std::path::Path;

pub fn export_sfz(
    preset: &Patch,
    bank: &WavetableBank,
    out_path: &Path,
    opts: &ExportOptions,
) -> ExportReport {
    let sfz_dir = out_path.parent().unwrap_or_else(|| Path::new("."));
    let samples_dir = sfz_dir.join("samples");
    if let Err(e) = std::fs::create_dir_all(&samples_dir) {
        return ExportReport::fail("sfz", e.to_string());
    }

    let sample_name = format!("{}_{}.wav", sanitize_name(&preset.name), opts.midi_note);
    let sample_path = samples_dir.join(&sample_name);
    let mono = render_note(bank, opts.freq, opts.duration, opts.sample_rate, preset);
    if let Err(e) = crate::export::wav::write_wav_mono(&sample_path, &mono, opts.sample_rate) {
        return ExportReport::fail("sfz", e);
    }

    let mut dropped = Vec::new();
    if !preset.mod_matrix.is_empty() {
        dropped.push(crate::export::DroppedParam {
            path: "mod_matrix".into(),
            reason: "SFZ v1 uses sample + basic filter opcodes only".into(),
        });
    }

    let sfz = format!(
        "// Generated by ReelSynth export\n\
<group>\n\
ampeg_attack={:.4}\n\
ampeg_release={:.4}\n\
cutoff={:.1}\n\
resonance={:.3}\n\
\n\
<region>\n\
sample=samples/{sample_name}\n\
pitch_keycenter={}\n\
lokey=0\n\
hikey=127\n\
",
        preset.envelope.attack,
        preset.envelope.release,
        preset.filter.cutoff,
        preset.filter.resonance,
        opts.midi_note,
    );

    if let Some(parent) = out_path.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            return ExportReport::fail("sfz", e.to_string());
        }
    }
    match std::fs::write(out_path, sfz) {
        Ok(()) => ExportReport::ok("sfz", out_path.display().to_string()).with_dropped(dropped),
        Err(e) => ExportReport::fail("sfz", e.to_string()),
    }
}

fn sanitize_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_ascii_lowercase()
}
