use std::collections::HashSet;

use reelsynth::{ScopeLiveTaps, WavetableBank};

use crate::fx_rack::{default_effect_slots, EffectSlotUi};
use crate::mod_matrix::{default_mod_slots, ModSlotUi};
use crate::scope_strip::ScopeStripState;
use crate::wt::{morph_amount_for_position, WtEditTool};

#[derive(Debug, Clone, Copy, Default)]
pub struct ShellConfig {
    pub show_wt_editor: bool,
    pub show_osc_column: bool,
    pub show_mod_matrix: bool,
    pub show_fx_rack: bool,
}

#[derive(Default)]
pub struct ShellActions {
    pub params_changed: bool,
    pub note_on: Option<u8>,
    pub note_off: Option<u8>,
    pub open_preset: bool,
    pub save_preset: bool,
    pub import_wt_file: bool,
    pub save_wt_file: bool,
    pub import_factory_wt: Option<String>,
    pub import_vital_wt: bool,
    pub import_wav_folder: bool,
    pub import_serum_fxp: bool,
    pub frame_edited: bool,
    pub midi_device_selected: Option<usize>,
}

pub struct ShellMidiDevices<'a> {
    pub names: &'a [String],
    pub selected: usize,
}

pub struct UiState {
    pub wt_position: f32,
    pub osc_position: [f32; 3],
    pub wt_bank_name: String,
    pub wt_edit_tool: WtEditTool,
    pub wt_morph_a: f32,
    pub wt_morph_b: f32,
    pub wt_morph_amount: f32,
    pub osc_morph_a: [f32; 3],
    pub osc_morph_b: [f32; 3],
    pub osc_morph_amount: [f32; 3],
    pub osc_tab: usize,
    pub osc_type: [usize; 3],
    pub osc_level: [f32; 3],
    pub osc_pan: [f32; 3],
    pub osc_coarse: [f32; 3],
    pub osc_unison: [u32; 3],
    pub osc_pulse_width: [f32; 3],
    pub osc_warp_mode: [usize; 3],
    pub osc_warp_amount: [f32; 3],
    pub osc_fm_source: [usize; 3],
    pub osc_fm_algorithm: [usize; 3],
    pub osc_fm_ratio: [f32; 3],
    pub osc_fm_index: [f32; 3],
    pub unison_stereo_spread: f32,
    pub sub_level: f32,
    pub noise_level: f32,
    pub macro_values: [f32; 4],
    pub filter_cutoff: f32,
    pub filter_resonance: f32,
    pub filter_key_tracking: f32,
    pub filter_drive: f32,
    pub filter2_cutoff: f32,
    pub filter2_resonance: f32,
    pub filter2_mode: usize,
    pub filter2_drive: f32,
    pub filter_mode: usize,
    pub env_attack: f32,
    pub env_decay: f32,
    pub env_sustain: f32,
    pub env_release: f32,
    pub filt_env_attack: f32,
    pub filt_env_decay: f32,
    pub filt_env_sustain: f32,
    pub filt_env_release: f32,
    pub lfo_rate: f32,
    pub lfo_depth: f32,
    pub lfo_shape: usize,
    pub lfo2_rate: f32,
    pub lfo2_depth: f32,
    pub lfo2_shape: usize,
    pub mod_matrix_open: bool,
    pub fx_rack_open: bool,
    pub mod_routes: Vec<ModSlotUi>,
    pub fx_slots: Vec<EffectSlotUi>,
    pub mod_route_total: usize,
    pub keys_down: HashSet<u8>,
    pub piano_visible: bool,
    pub preset_name: String,
    pub preset_category: String,
    pub status: String,
    pub midi_device: String,
}

pub struct ScopeStripContext<'a> {
    pub banks: &'a [WavetableBank],
    pub bank_for_osc: &'a dyn Fn(usize) -> usize,
    pub live: Option<&'a ScopeLiveTaps>,
    pub is_playing: bool,
    pub now_secs: f64,
    pub state: &'a mut ScopeStripState,
}

impl Default for UiState {
    fn default() -> Self {
        Self {
            wt_position: 108.0,
            osc_position: [108.0, 0.0, 0.0],
            wt_bank_name: "Saw Morph".into(),
            wt_edit_tool: WtEditTool::Select,
            wt_morph_a: 0.0,
            wt_morph_b: 255.0,
            wt_morph_amount: morph_amount_for_position(0.0, 255.0, 108.0),
            osc_morph_a: [0.0; 3],
            osc_morph_b: [255.0; 3],
            osc_morph_amount: [0.0; 3],
            osc_tab: 0,
            osc_type: [0, 0, 0],
            osc_level: [0.85, 0.0, 0.0],
            osc_pan: [0.0, 0.0, 0.0],
            osc_coarse: [0.0, 0.0, 0.0],
            osc_unison: [3, 1, 1],
            osc_pulse_width: [0.5, 0.5, 0.5],
            osc_warp_mode: [0, 0, 0],
            osc_warp_amount: [0.0, 0.0, 0.0],
            osc_fm_source: [0, 0, 0],
            osc_fm_algorithm: [0, 0, 0],
            osc_fm_ratio: [1.0, 1.0, 1.0],
            osc_fm_index: [0.0, 0.0, 0.0],
            unison_stereo_spread: 0.7,
            sub_level: 0.0,
            noise_level: 0.0,
            macro_values: [0.5; 4],
            filter_cutoff: 1200.0,
            filter_resonance: 0.3,
            filter_key_tracking: 0.5,
            filter_drive: 0.0,
            filter2_cutoff: 2400.0,
            filter2_resonance: 0.25,
            filter2_mode: 0,
            filter2_drive: 0.0,
            filter_mode: 0,
            env_attack: 0.012,
            env_decay: 0.22,
            env_sustain: 0.6,
            env_release: 0.4,
            filt_env_attack: 0.005,
            filt_env_decay: 0.35,
            filt_env_sustain: 0.2,
            filt_env_release: 0.5,
            lfo_rate: 2.4,
            lfo_depth: 0.0,
            lfo_shape: 0,
            lfo2_rate: 1.0,
            lfo2_depth: 0.0,
            lfo2_shape: 0,
            mod_matrix_open: true,
            fx_rack_open: true,
            mod_routes: default_mod_slots(),
            fx_slots: default_effect_slots(),
            mod_route_total: 24,
            keys_down: HashSet::new(),
            piano_visible: true,
            preset_name: "Factory Lead".into(),
            preset_category: "Bass · Wavetable · Saw Morph".into(),
            status: "Audio OK — click keys or use QWERTY row (Z–M)".into(),
            midi_device: "Default".into(),
        }
    }
}
